name: dev-deploy
on: [workflow_dispatch]

jobs:
  aws:
    name: Deploy To AWS
    environment:
      name: aws
    runs-on: ubuntu-latest

    steps:
    - uses: hashicorp/setup-terraform@v1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get State
      env:
        S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      run: |
        cd dev-terraform
        aws s3 sync "${S3_BUCKET}" . --exclude "*" --include "dev-terraform.tfstate" &>/dev/null
        mv dev-terraform.tfstate terraform.tfstate

    - name: Save Secrets
      env: 
        VPC_ID: ${{ secrets.AWS_VPC_ID }}
        KEY_PAIR_NAME: ${{ secrets.AWS_KEY_PAIR_NAME }}
        SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP }}
        REGION: ${{ secrets.AWS_REGION }}
      run: |
          envsubst < dev-terraform/main.tf > tempsecret
          cat tempsecret > dev-terraform/main.tf
          rm tempsecret

    - name: Terraform Init
      env:
        TF_ACTION_WORKING_DIR: 'dev-terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
          cd dev-terraform
          terraform init

    - name: Terraform Apply
      env:
        TF_ACTION_WORKING_DIR: 'dev-terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
          cd dev-terraform
          terraform apply -auto-approve  &>/dev/null

    - name: Publish State
      env:
        S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      run: |
        mv dev-terraform/terraform.tfstate dev-terraform/dev-terraform.tfstate
        aws s3 sync dev-terraform "${S3_BUCKET}" --exclude "*" --include "dev-terraform.tfstate" &>/dev/null
